//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleEF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mahasiswa
    {
        public string Nim { get; set; }
        public string Nama { get; set; }
        public string Alamat { get; set; }
        public double IPK { get; set; }
        public int KotaId { get; set; }
    
        public virtual Kota Kota { get; set; }
    }
}
